baseURL = "https://example.com"
title = "PT Courses"
author = "Pravesh Tamang"
copyright = "Copyright Â© 2020, Root; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
  
theme = "the-roots-home"

#enableGitInfo=true
enableEmoji= true
enableRobotsTXT= true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "vs"
[pygmentsOptions]
  linenos= true

[markup]
  defaultMarkdownHandler= "goldmark"
